### ISSUE TITLE
dssp plugin

### ISSUE THREAD

**Issue by biotech70** [Pymol-Scripts/Pymol-script-repo#115] opened 2020-11-01 16:10 UTC
What is the cause of the following error in dssp plugin?
```
dssp_stride.py", line 113, in <lambda>
    command=lambda s=self: DSSPPlugin(s))
  File "/home/proteininstitute/.pymol/startup/dssp_stride.py", line 261, in __init__
    self.notebook = Pmw.NoteBook(self.dialog.interior())
  File "/usr/local/lib/python3.8/dist-packages/Pmw/Pmw_2_0_1/lib/PmwNoteBook.py", line 60, in __init__
    Pmw.Color.bordercolors(self, self['hull_background'])
  File "/usr/local/lib/python3.8/dist-packages/Pmw/Pmw_2_0_1/lib/PmwColor.py", line 359, in bordercolors
    '#%04x%04x%04x' % (lightRGB[0], lightRGB[1], lightRGB[2]),
TypeError: %x format: an integer is required, not float
```

**Comment by speleo3** [comment] 2020-11-02 07:50
https://sourceforge.net/p/pmw/bugs/51/

https://github.com/schrodinger/pmw-patched

**Comment by biotech70** [comment] 2020-11-02 13:44
> https://sourceforge.net/p/pmw/bugs/51/
> 
> https://github.com/schrodinger/pmw-patched

Thanks for your tips. I downloaded the files in the *https://github.com/schrodinger/pmw-patched* address and put them in path of Python3.6, 3.7, and 3.8 but got the error again.

**Comment by biotech70** [comment] 2020-11-02 13:44
Thanks for your tips. I downloaded the files in the *https://github.com/schrodinger/pmw-patched* address and put them in path of Python3.6, 3.7, and 3.8 but got the error again.

**Comment by speleo3** [comment] 2020-11-02 13:54
You probably need to remove the `/usr/local/lib/python3.8/dist-packages/Pmw` folder.

**Comment by biotech70** [comment] 2020-11-02 16:10
its my python 3.8 directory content
![Untitled](https://user-images.githubusercontent.com/73783725/97890744-283c8000-1d43-11eb-9acc-3f56e6bafe65.png)

**Comment by speleo3** [comment] 2024-03-23 18:42
Duplicate of https://github.com/Pymol-Scripts/Pymol-script-repo/issues/122

**Closed by speleo3** 2024-03-23 18:42 UTC
